# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsFulltextIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=60)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectionsIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=60)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=60)),
                ('search_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_url', models.CharField(max_length=255, unique=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('prep_time', models.IntegerField(null=True)),
                ('cook_time', models.IntegerField(null=True)),
                ('total_time', models.IntegerField(null=True)),
                ('directions', models.TextField(null=True)),
                ('ingredients', models.ManyToManyField(to='searchengine.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='directionsindex',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchengine.Recipe'),
        ),
        migrations.AddField(
            model_name='directionsfulltextindex',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchengine.Recipe'),
        ),
    ]
