# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0006_auto_20170501_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
