# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0007_auto_20170501_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=60)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchengine.Ingredient')),
            ],
        ),
    ]
