# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0008_ingredientindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
