# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0009_recipe_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StemScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=30)),
                ('idf', models.FloatField()),
            ],
        ),
    ]
