# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0010_stemscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemscore',
            name='id',
        ),
        migrations.AlterField(
            model_name='stemscore',
            name='stem',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
